import type { Metadata } from "next";
import {Quicksand } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
      <Toaster
        position="bottom-right"
        reverseOrder={false}
      />
        {children}
        </body>
    </html>
  );
}
